exports.GET_SESSION_PENDING = 'GET_SESSION_PENDING'
exports.GET_SESSION_SUCCESSFUL = 'GET_SESSION_SUCCESSFUL'
exports.GET_SESSION_ERROR = 'GET_SESSION_ERROR'

// login
exports.POST_SESSION_PENDING = 'POST_SESSION_PENDING'
exports.POST_SESSION_SUCCESSFUL = 'POST_SESSION_SUCCESSFUL'
exports.POST_SESSION_ERROR = 'POST_SESSION_ERROR'

// logout
exports.DELETE_SESSION_PENDING = 'DELETE_SESSION_PENDING'
exports.DELETE_SESSION_SUCCESSFUL = 'DELETE_SESSION_SUCCESSFUL'
exports.DELETE_SESSION_ERROR = 'DELETE_SESSION_ERROR'
